### ISSUE TITLE
Doesn't work with app based 2FA

### ISSUE THREAD

**Issue by triblondon** [jakearchibald/tweetdeck-prototype#45]
It even told me to go away.  How rude.

**Comment by ahume** [comment]
Sorry, well harsh. Two things here.

Firstly change message to say 'waiting for mobile app auth', rather than 'go away', because we do actually support it.

However, when I just tried, it didn't push me the login request to iOS. I had to go into the security settings on the app, where the request was waiting to be authorised.

@triblondon You might want to see if that works in the meantime, as I don't know why it didn't push the request. Also, were you running this locally or on http://jakearchibald.github.io/tweetdeck-prototype/ ?

**Comment by triblondon** [comment]
I was on the github pages site.  You're right, the login request is in the settings panel.  When I accept it, the app stops telling me to get out and just displays an infinite spinner.  The following appears in the console:

![image](https://cloud.githubusercontent.com/assets/1735391/5776036/38127b1e-9d7a-11e4-98b9-1805315d56f7.png)

**Comment by ahume** [comment]
Hmm - I hadn't considered this scenario. The auth has worked, but the prototype isn't actually able to create you a *new* TweetDeck account in the backend, because it requires queuing a bunch of create requests from the client, which we're not likely to implement here.

@phuu I'm thinking the actual fix for this is stop using the TweetDeck API, but then... yeah, this is such a prototype.

@triblondon Meanwhile, if you log into *actual* TweetDeck with your account first, and then in to the prototype, this error should go away.

**Comment by tgvashworth** [comment]
Perhaps we could spin up a new app and request XAuth, and keep the token secret with the proxy on heroku.

**Comment by triblondon** [comment]
Ah, is this because I'm a laggard who hasn't converted their tweetdeck
account into a twitter account yet?

**Comment by ahume** [comment]
Well, it's because we didn't consider a situation that someone without a Twitter backed TweetDeck account would ever use the app. :)

But yes - if you go through the migration flow (Settings->Start using Twitter login) in TweetDeck that should solve the problem.

Until the next problem.

**Comment by triblondon** [comment]
Think we can close this.

**Comment by tgvashworth** [comment]
Haha! Thanks.

**Comment by ahume** [comment]
You mean it's working now, Andrew? ;)

**Comment by passy** [comment]
![](http://fanaru.com/robin-williams/image/53143-robin-williams-what-year-is-it.gif)

**Comment by triblondon** [comment]
When I give up on something I like to do it officially.

**Comment by ahume** [comment]
Never give up on TweetDeck.

Am I right, Tom?

**Comment by passy** [comment]
Never let down TweetDeck.
